name: senior_ease
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  google_sign_in: ^7.2.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^6.0.0

  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3
  provider: ^6.1.2
  state_notifier: ^1.0.0
  flutter_state_notifier: ^1.0.0
  get_it: ^9.2.0
  google_fonts: ^8.0.1
  url_launcher: ^6.3.1
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  image: ^4.8.0
  intl: ^0.20.2
  flutter_secure_storage: ^10.3.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  nested: ^1.0.0

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/img-loading-initial.svg
    - lib/assets/logo.svg
    - lib/assets/back.svg
    - lib/assets/bin.svg
    - lib/assets/check.svg
    - lib/assets/contrast.svg
    - lib/assets/edit.svg
    - lib/assets/foward.svg
    - lib/assets/logo-dark.svg
    - lib/assets/logout.svg
    - lib/assets/navigation.svg
    - lib/assets/steps.svg
    - lib/assets/text.svg
    - lib/assets/undo.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: fonts/Roboto-Bold.ttf
          weight: 700